### ISSUE TITLE
Memory Usage

### ISSUE THREAD

**Issue by chrimbo** [biemster/3keys_1knob#6]
Hi, can you just tell the current memory usage?

**Comment by biemster** [comment]
I'm traveling currently, so not able to check this. but just running the Makefile should give you this info.

**Comment by chrimbo** [comment]
Nope, would need to install compiler and stuff, which I currently don't have.

**Comment by chrimbo** [comment]
For the records:
```
FLASH: 3355 bytes
IRAM:  26 bytes
XRAM:  274 bytes
```

or for the extra branch from https://github.com/eworm-de/3keys_1knob/
```
FLASH: 3296 bytes
IRAM:  35 bytes
XRAM:  274 bytes
```
